theme: jekyll-theme-slate
title: Blue Scarab
description: A Data Analytics Company


lsi: false
safe: true
source: bluescarabio.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
